`timescale 1ns/1ps

import axi_vip_pkg::*;
import axi_vip_0_pkg::*;  // generated by Vivado when you add VIP

module tb_axi_fifo;

    // Clock and reset
    reg aclk;
    reg aresetn;

    // AXI VIP master agent
    axi_vip_0_mst_t   master_agent;

    // DUT signals
    wire [3:0]  m_axi_awaddr;
    wire [2:0]  m_axi_awprot;
    wire        m_axi_awvalid;
    wire        m_axi_awready;
    wire [31:0] m_axi_wdata;
    wire [3:0]  m_axi_wstrb;
    wire        m_axi_wvalid;
    wire        m_axi_wready;
    wire [1:0]  m_axi_bresp;
    wire        m_axi_bvalid;
    wire        m_axi_bready;
    wire [3:0]  m_axi_araddr;
    wire [2:0]  m_axi_arprot;
    wire        m_axi_arvalid;
    wire        m_axi_arready;
    wire [31:0] m_axi_rdata;
    wire [1:0]  m_axi_rresp;
    wire        m_axi_rvalid;
    wire        m_axi_rready;

    wire [15:0] gpio_in;
    wire [15:0] gpio_out;

    reg [15:0] gpio_in_r;
    assign gpio_in = gpio_in_r;

    // -------------------------------------------------------------------------
    // AXI VIP instance (Master)
    // -------------------------------------------------------------------------
    axi_vip_0 u_axi_vip (
        .aclk           (aclk),
        .aresetn        (aresetn),
        .m_axi_awaddr   (m_axi_awaddr),
        .m_axi_awprot   (m_axi_awprot),
        .m_axi_awvalid  (m_axi_awvalid),
        .m_axi_awready  (m_axi_awready),
        .m_axi_wdata    (m_axi_wdata),
        .m_axi_wstrb    (m_axi_wstrb),
        .m_axi_wvalid   (m_axi_wvalid),
        .m_axi_wready   (m_axi_wready),
        .m_axi_bresp    (m_axi_bresp),
        .m_axi_bvalid   (m_axi_bvalid),
        .m_axi_bready   (m_axi_bready),
        .m_axi_araddr   (m_axi_araddr),
        .m_axi_arprot   (m_axi_arprot),
        .m_axi_arvalid  (m_axi_arvalid),
        .m_axi_arready  (m_axi_arready),
        .m_axi_rdata    (m_axi_rdata),
        .m_axi_rresp    (m_axi_rresp),
        .m_axi_rvalid   (m_axi_rvalid),
        .m_axi_rready   (m_axi_rready)
    );

    // -------------------------------------------------------------------------
    // DUT
    // -------------------------------------------------------------------------
    axi_fifo #(
        .C_AXI_ADDR_WIDTH(4),
        .OPT_LOWPOWER(0)
    ) u_dut (
        .S_AXI_ACLK     (aclk),
        .S_AXI_ARESETN  (aresetn),
        .S_AXI_AWADDR   (m_axi_awaddr),
        .S_AXI_AWPROT   (m_axi_awprot),
        .S_AXI_AWVALID  (m_axi_awvalid),
        .S_AXI_AWREADY  (m_axi_awready),
        .S_AXI_WDATA    (m_axi_wdata),
        .S_AXI_WSTRB    (m_axi_wstrb),
        .S_AXI_WVALID   (m_axi_wvalid),
        .S_AXI_WREADY   (m_axi_wready),
        .S_AXI_BRESP    (m_axi_bresp),
        .S_AXI_BVALID   (m_axi_bvalid),
        .S_AXI_BREADY   (m_axi_bready),
        .S_AXI_ARADDR   (m_axi_araddr),
        .S_AXI_ARPROT   (m_axi_arprot),
        .S_AXI_ARVALID  (m_axi_arvalid),
        .S_AXI_ARREADY  (m_axi_arready),
        .S_AXI_RDATA    (m_axi_rdata),
        .S_AXI_RRESP    (m_axi_rresp),
        .S_AXI_RVALID   (m_axi_rvalid),
        .S_AXI_RREADY   (m_axi_rready),
        .gpio_in        (gpio_in),
        .gpio_out       (gpio_out)
    );

    // -------------------------------------------------------------------------
    // Clock
    // -------------------------------------------------------------------------
    initial aclk = 0;
    always #5 aclk = ~aclk;  // 100MHz

    // -------------------------------------------------------------------------
    // Helper tasks - mirrors your Verilator axi_write / axi_read
    // -------------------------------------------------------------------------
    task axi_write(
        input [31:0] addr,
        input [31:0] data
    );
        xil_axi_resp_t resp;
        xil_axi_ulong  wr_addr;
        xil_axi_data_beat wr_data;
        
        wr_addr = addr;
        wr_data = data;
        
        master_agent.AXI4LITE_WRITE_BURST(
            wr_addr,  // must be xil_axi_ulong type
            0,        // prot
            wr_data,  // must be xil_axi_data_beat type
            resp
        );
        if (resp !== XIL_AXI_RESP_OKAY)
            $display("WRITE ERROR: addr=0x%08x resp=%0d", addr, resp);
    endtask
    
    task axi_read(
        input  [31:0] addr,
        output [31:0] data
    );
        xil_axi_resp_t    resp;
        xil_axi_ulong     rd_addr;
        xil_axi_data_beat rd_data;
    
        rd_addr = addr;
    
        master_agent.AXI4LITE_READ_BURST(
            rd_addr,  // must be xil_axi_ulong type
            0,        // prot
            rd_data,  // must be xil_axi_data_beat type
            resp
        );
        data = rd_data[31:0];
        if (resp !== XIL_AXI_RESP_OKAY)
            $display("READ ERROR: addr=0x%08x resp=%0d", addr, resp);
    endtask

    // -------------------------------------------------------------------------
    // Main test
    // -------------------------------------------------------------------------
    integer i;
    reg [31:0] read_data;

    initial begin
        // init
        aresetn    = 0;
        gpio_in_r  = 0;

        // create and start VIP agent
        master_agent = new("master vip agent", 
                           u_axi_vip.inst.IF);
        master_agent.start_master();

        // reset
        repeat(5) @(posedge aclk);
        aresetn = 1;
        repeat(5) @(posedge aclk);

        $display("=== TEST 1: Write GPIO output (r1 @ 0x4) ===");
        axi_write(32'h4, 32'h00001234);
        @(posedge aclk);
        if (gpio_out !== 16'h1234)
            $display("FAIL: gpio_out=0x%04x expected 0x1234", gpio_out);
        else
            $display("PASS: gpio_out=0x%04x", gpio_out);

        $display("=== TEST 2: Readback r1 ===");
        axi_read(32'h4, read_data);
        if (read_data !== 32'h00001234)
            $display("FAIL: read=0x%08x expected 0x00001234", read_data);
        else
            $display("PASS: r1 readback=0x%08x", read_data);

        $display("=== TEST 3: gpio_in readback (r0 @ 0x0) ===");
        gpio_in_r = 16'hABCD;
        @(posedge aclk);
        axi_read(32'h0, read_data);
        if (read_data !== 32'h0000ABCD)
            $display("FAIL: read=0x%08x expected 0x0000ABCD", read_data);
        else
            $display("PASS: gpio_in readback=0x%08x", read_data);

        $display("=== TEST 4: FIFO write x3 then read x3 ===");
        axi_write(32'h8, 32'h1234ABCD);
        axi_write(32'h8, 32'h12340001);
        axi_write(32'h8, 32'h12340002);

        repeat(5) @(posedge aclk);

        axi_read(32'h8, read_data);
        $display("FIFO read 0: 0x%08x (expected 0x1234ABCD)", read_data);
        if (read_data !== 32'h1234ABCD)
            $display("FAIL");
        else
            $display("PASS");

        axi_read(32'h8, read_data);
        $display("FIFO read 1: 0x%08x (expected 0x12340001)", read_data);
        if (read_data !== 32'h12340001)
            $display("FAIL");
        else
            $display("PASS");

        axi_read(32'h8, read_data);
        $display("FIFO read 2: 0x%08x (expected 0x12340002)", read_data);
        if (read_data !== 32'h12340002)
            $display("FAIL");
        else
            $display("PASS");
            
        repeat(10) @(posedge aclk);
        $display("=== All tests done ===");
        $finish;
    end
    
endmodule